version: '3.4'

services:
  hackyeah.app.api:
    image: ${DOCKER_REGISTRY-}hackyeahappapi
    build:
      context: .
      dockerfile: hackyeah.App.API/Dockerfile
    ports:
        - "5015:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
